favorite_places = ['Qingdao', 'Shanghai', 'Tokyo', 'New York', 'London']
print(favorite_places)
print(sorted(favorite_places))
print(favorite_places)
print(sorted(favorite_places, reverse=True))
print(favorite_places)
favorite_places.reverse()
print(favorite_places)
favorite_places.reverse()
print(favorite_places)
favorite_places.sort()
print(favorite_places)
favorite_places.sort(reverse=True)
print(favorite_places)
